name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22.x
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm build
      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out
      - name: Set credentials
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_HOSTS: ${{ secrets.SSH_HOSTS }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          echo "$SSH_CONFIG" > ~/.ssh/config
          echo "$SSH_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_rsa
      - name: Sync files
        run: pnpm run deploy
